name: Build Manjusaka

on:
  push:
    branches:
      - main

env:
  MANJUSAKA_BIN: manjusaka

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build busybox
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential \
          ca-certificates \
          git \
          libncurses-dev \
          openssl \
          wget
        git clone https://github.com/mirror/busybox.git
        cd busybox
        make defconfig
        make -j$(nproc)
        cd ..

    - name: Build curl
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential \
          ca-certificates \
          git \
          libssl-dev \
          wget
        git clone https://github.com/curl/curl.git
        cd curl
        ./buildconf
        ./configure --disable-shared
        make -j$(nproc)
        cd ..

    - name: Package binaries
      run: |
        mkdir -p dist
        cp busybox/busybox curl/src/curl dist/$MANJUSAKA_BIN
        chmod +x dist/$MANJUSAKA_BIN

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: manjusaka
        path: dist/ 
