name: Build manjusaka

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download busybox source code
      run: |
        curl -L https://busybox.net/downloads/busybox-1.36.0.tar.bz2 -o busybox-1.36.0.tar.bz2
        tar xjf busybox-1.36.0.tar.bz2

    - name: Download curl source code
      run: |
        curl -L https://curl.se/download/curl-7.88.1.tar.bz2 -o curl-7.88.1.tar.bz2
        tar xjf curl-7.88.1.tar.bz2

    - name: Compile busybox
      run: |
        cd busybox-1.36.0
        make defconfig
        make -j $(nproc)

    - name: Compile curl
      run: |
        cd curl-7.88.1
        ./buildconf
        ./configure --without-libssh2 --disable-shared --enable-static --prefix=$PWD/output
        make -j $(nproc)
        make install

    - name: Create binary file
      run: |
        cd busybox-1.36.0/_install
        cp bin/busybox ../manjusaka
        cp ../../curl-7.88.1/output/bin/curl ../manjusaka
        chmod +x ../manjusaka

    - name: Define custom command
      run: |
        export RUN_CMD="./manjusaka -c"
